import re
import time

import Links
from playwright.sync_api import Page, expect
from utils.custom_wait import wait_for_element
import allure
import pytest
from playwright.sync_api import Playwright, sync_playwright, expect
from config import BASE_URL, LOGIN_PAGE, USERNAME, PASSWORD, WAIT_TIME, setup_browser_and_context
from core.BaseTest import authorization
from playwright.sync_api import Page, expect


def crate_project_prms(page):
    # Создание проекта PRMS
    page.get_by_role("button", name="Создать новый проект").click()
    expect(page.get_by_label("Without label")).to_contain_text("РКЗ")
    page.get_by_label("Without label").click()
    expect(page.get_by_role("option", name="РКЗ")).to_be_visible()
    expect(page.get_by_role("option", name="РКООН")).to_be_visible()
    expect(page.get_by_role("option", name="PRMS")).to_be_visible()
    page.get_by_role("option", name="PRMS").click()
    expect(page.get_by_role("button", name="Добавить")).to_be_visible()
    expect(page.get_by_role("button", name="Загрузить из шаблона")).to_be_visible()
    expect(page.get_by_role("button", name="Загрузить из файла")).to_be_visible()
    expect(page.get_by_text("Результат конвертацииCreated")).to_be_visible()
    expect(page.locator("span").filter(has_text="Created with Pixso.Конвертировать")).to_be_visible()
    page.get_by_role("button", name="Добавить").click()



    page.locator("input[name=\"Месторождение\"]").click()
    page.locator("input[name=\"Месторождение\"]").fill("Казанское")
    page.locator("input[name=\"Месторождение\"]").press("Enter")
    page.locator("div:nth-child(2) > .MuiInputBase-root > .MuiSelect-select").click()
    page.get_by_role("option", name="Газоконденсатное", exact=True).click()
    page.locator("input[name=\"Группа эксплуатационных объектов\"]").click()
    page.locator("input[name=\"Группа эксплуатационных объектов\"]").fill("Юра")
    page.locator("input[name=\"Группа эксплуатационных объектов\"]").press("Enter")
    page.locator("input[name=\"Эксплуатационный объект\"]").click()
    page.locator("input[name=\"Эксплуатационный объект\"]").fill("ГРН6")
    page.get_by_role("option", name="ГРН").click()
    page.locator("input[name=\"Пласт\"]").click()
    page.locator("input[name=\"Пласт\"]").fill("ГРО_2")
    page.locator("input[name=\"Пласт\"]").press("Enter")
    page.locator("input[name=\"Залежь\"]").click()
    page.locator("input[name=\"Залежь\"]").fill("ГРО_!")
    page.get_by_role("option", name="ГРО_!").click()

    page.get_by_role("button", name="Дополнительные параметры").click()
    page.locator("input[name=\"Страна\"]").click()
    page.get_by_role("option", name="Исландия").click()
    page.locator("input[name=\"Регион\"]").click()
    page.locator("input[name=\"Регион\"]").fill("44")
    page.get_by_role("option", name="44").click()
    page.locator("input[name=\"Собственник\"]").click()
    page.locator("input[name=\"Собственник\"]").fill("ПАО Газпром")
    page.locator("input[name=\"Собственник\"]").press("Enter")
    page.locator("#percentOwn").click()
    page.locator("#percentOwn").fill("67")
    page.locator("input[name=\"Недропользователь\"]").click()
    page.locator("input[name=\"Недропользователь\"]").click()
    page.locator("input[name=\"Недропользователь\"]").press("ControlOrMeta+м")
    page.locator("input[name=\"Оператор\"]").click()
    page.locator("input[name=\"Оператор\"]").press("ControlOrMeta+м")
    page.locator("input[name=\"Оператор\"]").press("Enter")
    page.locator(".MuiDialog-container").press("ArrowLeft")
    page.locator("input[name=\"Лицензионный участок\"]").click()
    page.locator("input[name=\"Лицензионный участок\"]").fill("ГРД")
    page.locator("input[name=\"Лицензионный участок\"]").press("Enter")
    page.locator("input[name=\"Лицензионные обязательства \\/ ограничения\"]").click()
    page.locator("input[name=\"Лицензионные обязательства \\/ ограничения\"]").click()
    page.locator("input[name=\"Лицензионные обязательства \\/ ограничения\"]").press("ControlOrMeta+м")
    page.locator("#yearOpen").click()
    page.locator("#yearOpen").fill("2000")
    page.locator("input[name=\"Метод подсчета\"]").click()
    page.get_by_role("option", name="Обьёмный").click()
    page.locator("input[name=\"Организация\\, выполнившая оценку\"]").click()
    page.get_by_role("option", name="ООО \"ВЫГОН Консалтинг\"").click()
    page.locator("input[name=\"Организация\\, выполнившая оценку\"]").press("Enter")
    page.locator("input[name=\"Отвественный исполнитель подсчета\"]").click()
    page.get_by_role("option", name="Отвественный исполнитель подсчета").click()
    page.locator("input[name=\"Отвественный исполнитель подсчета\"]").press("Enter")
    page.locator("input[name=\"Отвественный исполнитель подсчета\"]").click()
    page.get_by_role("option", name="подсчета исполнитель Отвественный").click()
    page.locator("input[name=\"Отвественный исполнитель подсчета\"]").press("Enter")
    page.locator("input[name=\"Отвественный исполнитель подсчета\"]").click()
    page.get_by_role("option", name="подсчета исполнитель Отвественный").click()
    page.locator("#countingData").fill("2024-12-24")
    expect(page.get_by_role("button", name="Далее")).to_be_visible()
    page.get_by_role("button", name="Далее").click()

    expect(page.get_by_role("button", name="Далее")).to_be_visible()
    page.get_by_role("button", name="Далее").click()
    page.locator("div:nth-child(2) > .MuiInputBase-root > .MuiSelect-select").first.click()
    page.get_by_text("Нефть, тыс.т").click()
    page.get_by_text("Газовая шапка, млн.м").click()
    page.get_by_role("option", name="Газ свободный, млн.м").get_by_role("checkbox").check()
    page.get_by_role("option", name="Конденсат в газовой шапке, тыс.т").get_by_role("checkbox").check()
    page.get_by_role("option", name="Конденсат в газовой шапке, тыс.т").press("Tab")
    page.locator("#parametersForm > div > div:nth-child(2) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select").click()
    page.get_by_text("Возможные - P3").click()
    page.get_by_text("Вероятные - P2").click()
    page.get_by_text("Низкая - C1").click()
    page.get_by_role("option", name="Низкая - C1").press("Tab")
    page.locator("#productionStartYear").click()
    page.locator("#productionStartYear").fill("2000")
    page.get_by_text("Запасы").click()
    page.get_by_role("option", name="Условные ресурсы").click()
    page.locator("div:nth-child(5) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select").click()
    page.get_by_role("option", name="Разработка приостановлена").click()
    page.get_by_text("Не определено").nth(1).click()
    page.get_by_text("Экономические неэффективные").click()
    page.get_by_role("option", name="Экономические неэффективные").press("Tab")
    expect(page.locator("#parametersForm")).to_contain_text("Экономические неэффективные")
    expect(page.get_by_role("button", name="Назад")).to_be_visible()
    page.get_by_role("button", name="Сохранить").click()
    page.get_by_role("button", name="Сохранить").click()
    expect(page.get_by_label("file system navigator").get_by_text("Казанское")).to_be_visible()