import re
import time

import Links
from playwright.sync_api import Page, expect

from test.test_Add_conversion_project.projects_page import crate_project_prms
from utils.custom_wait import wait_for_element
import allure
import pytest
from playwright.sync_api import Playwright, sync_playwright, expect
from config import BASE_URL, LOGIN_PAGE, USERNAME, PASSWORD, WAIT_TIME, setup_browser_and_context, BASE_PROJECT_PRMS
from core.BaseTest import authorization, del_project
from playwright.sync_api import Page, expect


# Просмотр страницы Главная, автотесты

@pytest.mark.test_all
def test_vive_projects_page(page: Page) -> None:
    browser, context, page = setup_browser_and_context()
    # Авторизация
    authorization(page)
    expect(page.get_by_role("heading", name="Конвертер запасов")).to_be_visible()
    expect(page.get_by_role("button", name="Все")).to_be_visible()
    page.get_by_role("button", name="РКООН").click()
    expect(page.get_by_role("button", name="РКЗ")).to_be_visible()

    context.close()
    browser.close()


@pytest.mark.test_all
def test_vive_all_classification(playwright: Playwright) -> None:
    browser, context, page = setup_browser_and_context(playwright)
    # Авторизация
    authorization(page)
    expect(page.get_by_text("Сортировать:Сначала новые")).to_be_visible()
    expect(page.locator("#root")).to_contain_text("Сортировать:")
    expect(page.get_by_role("button", name="Создать новый проект")).to_be_visible()
    expect(page.locator("#lists")).to_be_visible()
    expect(page.get_by_placeholder("Найти")).to_be_visible()
    expect(page.get_by_role("button", name="РКЗ")).to_be_visible()
    expect(page.get_by_role("button", name="PRMS")).to_be_visible()
    expect(page.get_by_role("button", name="РКООН")).to_be_visible()
    page.get_by_role("button", name="РКООН").click()
    page.get_by_role("button", name="Все").click()

    context.close()
    browser.close()


@pytest.mark.test_all
def test_vive_classification_pkz(playwright: Playwright) -> None:
    browser, context, page = setup_browser_and_context(playwright)
    # Авторизация
    authorization(page)
    expect(page.get_by_text("Сортировать:Сначала новые")).to_be_visible()
    expect(page.locator("#root")).to_contain_text("Сортировать:")
    expect(page.get_by_role("button", name="Создать новый проект")).to_be_visible()
    expect(page.locator("#lists")).to_be_visible()
    expect(page.get_by_placeholder("Найти")).to_be_visible()
    expect(page.get_by_role("button", name="РКЗ")).to_be_visible()
    page.get_by_role("button", name="РКЗ").click()
    page.get_by_role("button", name="Все").click()

    context.close()
    browser.close()


@pytest.mark.test_all
def test_vive_classification_prms(playwright: Playwright) -> None:
    browser, context, page = setup_browser_and_context(playwright)
    # Авторизация
    authorization(page)
    expect(page.get_by_text("Сортировать:Сначала новые")).to_be_visible()
    expect(page.locator("#root")).to_contain_text("Сортировать:")
    expect(page.get_by_role("button", name="Создать новый проект")).to_be_visible()
    expect(page.locator("#lists")).to_be_visible()
    expect(page.get_by_placeholder("Найти")).to_be_visible()
    expect(page.get_by_role("button", name="РКЗ")).to_be_visible()
    expect(page.get_by_role("button", name="PRMS")).to_be_visible()
    expect(page.get_by_role("button", name="РКООН")).to_be_visible()
    page.get_by_role("button", name="PRMS").click()
    page.get_by_role("button", name="Все").click()

    context.close()
    browser.close()


@pytest.mark.test_all
def test_vive_classification_prms(playwright: Playwright) -> None:
    browser, context, page = setup_browser_and_context(playwright)
    # Авторизация
    authorization(page)
    expect(page.get_by_text("Сортировать:Сначала новые")).to_be_visible()
    expect(page.locator("#root")).to_contain_text("Сортировать:")
    expect(page.get_by_role("button", name="Создать новый проект")).to_be_visible()
    expect(page.locator("#lists")).to_be_visible()
    expect(page.get_by_placeholder("Найти")).to_be_visible()
    expect(page.get_by_role("button", name="РКЗ")).to_be_visible()
    expect(page.get_by_role("button", name="PRMS")).to_be_visible()
    expect(page.get_by_role("button", name="РКООН")).to_be_visible()
    page.get_by_role("button", name="РКООН").click()
    page.get_by_role("button", name="Все").click()

    context.close()
    browser.close()


@pytest.mark.test_all
def test_projects_page_searсh(playwright: Playwright) -> None:
    browser, context, page = setup_browser_and_context(playwright)
    # Авторизация
    authorization(page)
    page.get_by_placeholder("Найти").click()
    page.get_by_placeholder("Найти").fill("Новый")
    page.get_by_placeholder("Найти").press("Enter")
    expect(page.locator("#root")).to_contain_text("Новый проект конвертации")

    context.close()
    browser.close()


@pytest.mark.test_all
def test_example_prz(playwright: Playwright) -> None:
    browser, context, page = setup_browser_and_context(playwright)
    # Авторизация
    authorization(page)
    page.get_by_role("button", name="Создать новый проект").click()
    expect(page.locator("h2")).to_be_visible()
    page.get_by_label("sidebar arrow").click()
    expect(page.get_by_role("heading", name="Мои проекты")).to_be_visible()

    context.close()
    browser.close()


@pytest.mark.test_all
def test_projects_page_crate_rks(playwright: Playwright) -> None:
    browser, context, page = setup_browser_and_context(playwright)
    # Авторизация
    authorization(page)
    page.get_by_role("button", name="Создать новый проект").click()

    context.close()
    browser.close()


@pytest.mark.test_all1
def test_projects_crate_prms(playwright: Playwright) -> None:
    browser, context, page = setup_browser_and_context(playwright)
    # Авторизация
    authorization(page)
    # Создание проект prms
    crate_project_prms(page)
    # Заполнение общей информации

    # Заполнение доп параметров

    # Заполнение параметров

    context.close()
    browser.close()


@pytest.mark.test_all
@pytest.mark.test_create_projects
def test_projects_page_crate_prms(playwright: Playwright) -> None:
    browser, context, page = setup_browser_and_context(playwright)
    # Авторизация
    authorization(page)

    page.get_by_role("button", name="Создать новый проект").click()
    expect(page.get_by_label("Without label")).to_contain_text("РКЗ")
    page.get_by_label("edit project name").click()
    page.get_by_role("main").get_by_placeholder("Найти").fill(BASE_PROJECT_PRMS)
    page.get_by_role("main").get_by_placeholder("Найти").press("Enter")
    expect(page.locator("h2")).to_contain_text(BASE_PROJECT_PRMS)
    page.get_by_label("Without label").click()
    expect(page.get_by_role("option", name="РКЗ")).to_be_visible()
    expect(page.get_by_role("option", name="РКООН")).to_be_visible()
    expect(page.get_by_role("option", name="PRMS")).to_be_visible()

    page.get_by_role("option", name="PRMS").click()
    expect(page.get_by_label("Without label")).to_contain_text("PRMS")
    page.locator("#menu- div").first.click()
    page.get_by_role("button", name="Добавить").click()
    expect(page.get_by_text("Месторождение*")).to_be_visible()
    expect(page.get_by_text("Тип месторождения")).to_be_visible()
    expect(page.get_by_text("Группа эксплуатационных объектов")).to_be_visible()
    expect(page.get_by_text("Эксплуатационный объект")).to_be_visible()
    expect(page.locator("#commonInfoForm div").filter(has_text="Пласт").nth(1)).to_be_visible()
    expect(page.locator("#commonInfoForm div").filter(has_text="Залежь").nth(1)).to_be_visible()
    page.locator("#commonInfoForm div").filter(has_text="Залежь").nth(1).click()
    page.get_by_text("Залежь").click()
    expect(page.locator("#panel1-header")).to_contain_text("Дополнительные параметрыCreated with Pixso.")
    page.get_by_role("button", name="Дополнительные параметры").click()
    expect(page.get_by_label("Дополнительные параметры").locator("div").filter(has_text="Страна").nth(2)).to_be_visible()
    expect(page.get_by_text("Регион")).to_be_visible()
    expect(page.get_by_text("Страна")).to_be_visible()
    expect(page.get_by_text("Собственник")).to_be_visible()
    expect(page.get_by_text("Доля участия в проекте, %")).to_be_visible()
    expect(page.get_by_text("Недропользователь")).to_be_visible()
    expect(page.get_by_text("Оператор")).to_be_visible()
    expect(page.get_by_text("Лицензионный участок")).to_be_visible()
    expect(page.get_by_text("Лицензионные обязательства / ограничения")).to_be_visible()
    expect(page.get_by_text("Год открытия")).to_be_visible()
    expect(page.get_by_text("Метод подсчета")).to_be_visible()
    expect(page.get_by_text("Организация, выполнившая оценку")).to_be_visible()
    expect(page.get_by_text("Отвественный исполнитель подсчета")).to_be_visible()
    expect(page.get_by_text("Дата, на которую подсчитаны запасы")).to_be_visible()
    expect(page.get_by_role("button", name="Далее")).to_be_visible()
    page.locator("input[name=\"Месторождение\"]").click()
    page.locator("input[name=\"Месторождение\"]").fill("Малыгинское")
    page.locator("input[name=\"Месторождение\"]").press("Enter")
    page.locator(".MuiDialog-container").press("Tab")
    page.locator("div:nth-child(2) > .MuiInputBase-root > .MuiSelect-select").click()
    page.get_by_role("option", name="Газоконденсатное", exact=True).click()
    page.locator("input[name=\"Группа эксплуатационных объектов\"]").click()
    page.locator("input[name=\"Группа эксплуатационных объектов\"]").fill("альб-неоком, юра")
    page.locator("input[name=\"Группа эксплуатационных объектов\"]").press("Enter")
    page.locator("input[name=\"Эксплуатационный объект\"]").click()
    page.locator("input[name=\"Эксплуатационный объект\"]").fill("альб-неоком, юра")
    page.locator("input[name=\"Эксплуатационный объект\"]").press("Enter")
    page.locator("input[name=\"Пласт\"]").click()
    page.locator("input[name=\"Пласт\"]").fill("Ю1/2")
    page.locator("input[name=\"Пласт\"]").press("Enter")
    page.locator("div:nth-child(6) > .MuiAutocomplete-root > .MuiFormControl-root > .MuiInputBase-root").first.click()
    page.locator("input[name=\"Залежь\"]").fill("Ю1")
    page.locator("input[name=\"Залежь\"]").press("Enter")
    page.locator("input[name=\"Страна\"]").click()
    page.get_by_role("option", name="Куба").click()
    page.locator("input[name=\"Регион\"]").click()
    page.locator("input[name=\"Регион\"]").fill("44")
    page.get_by_role("option", name="44").click()
    page.locator("input[name=\"Собственник\"]").click()
    page.locator("input[name=\"Собственник\"]").fill("ПАО Газпром")
    page.locator("#percentOwn").dblclick()
    page.locator("#percentOwn").fill("55")
    page.locator("input[name=\"Недропользователь\"]").click()
    page.locator("input[name=\"Недропользователь\"]").fill("ООО Газпром добыча Астрахань")
    page.locator("input[name=\"Недропользователь\"]").press("Tab")
    page.locator("input[name=\"Оператор\"]").click()
    page.locator("input[name=\"Оператор\"]").fill("ООО Газпром добыча Астрахань")

    page.locator("input[name=\"Лицензионный участок\"]").click()
    page.locator("input[name=\"Лицензионный участок\"]").fill("АСТ 14552 НР, АСТ 14553 НЭ")
    page.locator("input[name=\"Лицензионные обязательства \\/ ограничения\"]").fill("20.08.2008-31.12.2130, 20.08.2008-31.12.2222")
    page.locator("input[name=\"Лицензионные обязательства \\/ ограничения\"]").press("Enter")
    page.locator("#yearOpen").fill("2000")
    page.locator("input[name=\"Метод подсчета\"]").click()
    page.get_by_role("option", name="Объемный", exact=True).click()
    page.locator("input[name=\"Организация\\, выполнившая оценку\"]").click()
    page.get_by_role("option", name="ВНИИГАЗ").click()
    page.locator("input[name=\"Отвественный исполнитель подсчета\"]").click()
    page.get_by_role("option", name="Отвественный исполнитель подсчета").click()
    page.locator("#countingData").fill("2019-10-16")
    page.get_by_role("button", name="Далее").click()
    page.locator("div:nth-child(2) > .MuiInputBase-root > .MuiSelect-select").first.click()
    page.get_by_text("Газовая шапка, млн.м").click()
    page.get_by_role("option", name="Газ свободный, млн.м").get_by_role("checkbox").check()
    page.get_by_role("option", name="Газ свободный, млн.м").press("Tab")
    page.locator(
        "#parametersForm > div > div:nth-child(2) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select").click()
    page.get_by_text("Низкая - C1").click()
    page.get_by_role("option", name="Возможные - P3").get_by_role("checkbox").check()
    page.get_by_role("option", name="Вероятные - P2").get_by_role("checkbox").check()
    page.get_by_role("option", name="Вероятные - P2").get_by_role("checkbox").press("Tab")
    page.locator("#productionStartYear").click()
    page.locator("#productionStartYear").fill("2000")
    page.get_by_text("Условные ресурсы").click()
    page.get_by_role("option", name="Запасы").click()
    page.locator("div:nth-child(5) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select").click()
    page.get_by_role("option", name="Разработка ожидается").click()
    page.get_by_text("Не определено").first.click()
    page.get_by_text("PDNP", exact=True).click()
    page.get_by_role("option", name="PDP").get_by_role("checkbox").check()
    page.get_by_role("option", name="PDP").get_by_role("checkbox").press("Tab")
    page.get_by_role("button", name="Сохранить").click()
    page.get_by_role("button", name="Сохранить").dblclick()
    page.get_by_role("button", name="Сохранить").click(click_count=4)
    page.wait_for_load_state()
    page.get_by_role("heading", name="Запасы").is_visible()
    # expect(page.get_by_role("heading", name="Запасы")).to_be_visible(timeout=15_000)
    # time.sleep(4)
    del_project(page)

    context.close()
    browser.close()


@pytest.mark.test_all
@pytest.mark.test_create_projects
def test_projects_page_crate_prs(playwright: Playwright) -> None:
    browser, context, page = setup_browser_and_context(playwright)
    # Авторизация
    authorization(page)

    page.get_by_role("button", name="Создать новый проект").click()
    expect(page.get_by_label("Without label")).to_contain_text("РКЗ")
    page.get_by_label("edit project name").click()
    page.get_by_role("main").get_by_placeholder("Найти").fill(BASE_PROJECT_PRMS)
    page.get_by_role("main").get_by_placeholder("Найти").press("Enter")
    expect(page.locator("h2")).to_contain_text(BASE_PROJECT_PRMS)
    page.get_by_label("Without label").click()
    expect(page.get_by_role("option", name="РКЗ")).to_be_visible()
    expect(page.get_by_role("option", name="РКООН")).to_be_visible()
    expect(page.get_by_role("option", name="PRMS")).to_be_visible()
    page.get_by_role("option", name="РКЗ").click()
    page.get_by_role("button", name="Добавить").click()
    time.sleep(3)
    page.locator("input[name=\"Месторождение\"]").click()
    page.locator("input[name=\"Месторождение\"]").fill("1")
    page.locator("input[name=\"Месторождение\"]").press("Enter")
    page.locator("div:nth-child(2) > .MuiInputBase-root > .MuiSelect-select").click()
    page.get_by_role("option", name="Газоконденсатное", exact=True).click()
    page.locator("input[name=\"Группа эксплуатационных объектов\"]").click()
    page.locator("input[name=\"Группа эксплуатационных объектов\"]").fill("11")
    page.locator("input[name=\"Группа эксплуатационных объектов\"]").press("Enter")
    page.locator("div:nth-child(4) > .MuiAutocomplete-root > .MuiFormControl-root > .MuiInputBase-root").click()
    page.locator("input[name=\"Эксплуатационный объект\"]").fill("122")
    page.locator("input[name=\"Эксплуатационный объект\"]").press("Enter")
    page.locator("input[name=\"Пласт\"]").click()
    page.locator("input[name=\"Пласт\"]").fill("1222")
    page.locator("input[name=\"Пласт\"]").press("Enter")
    page.locator("input[name=\"Залежь\"]").click()
    page.locator("input[name=\"Залежь\"]").fill("1233")
    page.locator("input[name=\"Залежь\"]").press("Enter")
    expect(page.locator("#commonInfoForm")).to_contain_text("")
    expect(page.get_by_text("Месторождение*")).to_be_visible()
    expect(page.get_by_text("Тип месторождения")).to_be_visible()
    expect(page.get_by_text("Группа эксплуатационных объектов")).to_be_visible()
    expect(page.get_by_text("Эксплуатационный объект")).to_be_visible()
    expect(page.get_by_text("Пласт*")).to_be_visible()
    expect(page.get_by_text("Залежь")).to_be_visible()
    expect(page.get_by_role("button", name="Дополнительные параметры")).to_be_visible()
    page.get_by_role("button", name="Дополнительные параметры").click()
    page.locator("input[name=\"Страна\"]").click()
    page.get_by_role("option", name="Куба").click()
    page.locator("input[name=\"Страна\"]").press("Tab")
    page.locator("input[name=\"Страна\"]").press("Escape")
    page.locator("input[name=\"Регион\"]").click()
    page.locator("input[name=\"Регион\"]").fill("12")
    page.get_by_role("option", name="12").click()
    page.locator("input[name=\"Регион\"]").press("Enter")
    page.locator(".MuiAccordionDetails-root > div > div:nth-child(3) > .MuiAutocomplete-root > .MuiFormControl-root > .MuiInputBase-root").click()
    page.locator("input[name=\"Собственник\"]").fill("67")
    page.locator("input[name=\"Собственник\"]").press("Enter")
    page.locator("#percentOwn").click()
    page.locator("#percentOwn").fill("67")
    page.locator("#percentOwn").press("Enter")
    page.locator(".MuiAccordionDetails-root > div > div:nth-child(5) > .MuiAutocomplete-root > .MuiFormControl-root > .MuiInputBase-root").click()
    page.locator("input[name=\"Недропользователь\"]").fill("78")
    page.locator("input[name=\"Недропользователь\"]").press("Enter")
    page.locator(".MuiAccordionDetails-root > div > div:nth-child(6) > .MuiAutocomplete-root > .MuiFormControl-root > .MuiInputBase-root").click()
    page.locator("input[name=\"Оператор\"]").fill("678")
    page.locator("input[name=\"Оператор\"]").press("Enter")
    page.locator("div:nth-child(7) > .MuiAutocomplete-root > .MuiFormControl-root > .MuiInputBase-root").click()
    page.locator("input[name=\"Лицензионный участок\"]").fill("67")
    page.locator("input[name=\"Лицензионный участок\"]").press("Enter")
    page.locator("input[name=\"Лицензионные обязательства \\/ ограничения\"]").click()
    page.locator("input[name=\"Лицензионные обязательства \\/ ограничения\"]").fill("678")
    page.locator("input[name=\"Лицензионные обязательства \\/ ограничения\"]").press("Enter")
    page.locator("#yearOpen").click()
    page.locator("#yearOpen").fill("2000")
    page.locator("#yearOpen").press("Enter")
    page.get_by_text("СтранаРегионСобственникДоля участия в проекте, %НедропользовательОператорЛицензи").click()
    page.locator("input[name=\"Метод подсчета\"]").click()
    page.get_by_role("option", name="Объёмный").click()
    page.locator("input[name=\"Метод подсчета\"]").press("Enter")
    page.locator("input[name=\"Организация\\, выполнившая оценку\"]").click()
    page.get_by_role("option", name="Выгон Консалт", exact=True).click()
    page.locator("input[name=\"Организация\\, выполнившая оценку\"]").press("Enter")
    page.locator("div:nth-child(12) > .MuiAutocomplete-root > .MuiFormControl-root > .MuiInputBase-root").click()
    page.get_by_role("option", name="Долотова В.В").click()
    page.locator("input[name=\"Отвественный исполнитель подсчета\"]").press("Enter")
    page.locator("#countingData").fill("2024-12-26")
    page.locator("#countingData").press("Enter")
    page.get_by_role("button", name="Далее").click()
    expect(page.get_by_role("button", name="Назад")).to_be_visible()
    page.get_by_text("Нет проекта").first.click()
    page.get_by_role("option", name="ТПР", exact=True).click()
    time.sleep(3)
    page.get_by_text('Проектный документ на изучение*Нет проекта').click()
    page.get_by_role("option", name="Проект доразведки").click()
    page.locator("div:nth-child(3) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select").click()
    page.get_by_text("Газ свободный, млн.м").click()
    page.get_by_role("option", name="Газовая шапка, млн.м").get_by_role("checkbox").check()
    page.get_by_role("option", name="Растворенный газ, млн.м").get_by_role("checkbox").check()
    page.get_by_role("option", name="Нефть, тыс.т").get_by_role("checkbox").check()
    page.get_by_role("option", name="Конденсат в газовой шапке, тыс.т").get_by_role("checkbox").check()
    page.get_by_role("option", name="Конденсат в свободном газе, тыс.т").get_by_role("checkbox").check()
    page.get_by_role("option", name="Cера в нефти тыс.т").get_by_role("checkbox").check()
    page.get_by_role("option", name="Сера в растворенном газе, тыс.т").get_by_role("checkbox").check()
    page.get_by_role("option", name="Сера в растворенном газе, тыс.т").press("Enter")
    page.get_by_role("option", name="Cера в нефти тыс.т").press("Escape")
    page.locator("div:nth-child(4) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select").click()
    page.get_by_role("option", name="C1").get_by_role("checkbox").check()
    page.get_by_role("option", name="B3").get_by_role("checkbox").check()
    page.get_by_role("option", name="B2").get_by_role("checkbox").check()
    page.get_by_role("option", name="B1").get_by_role("checkbox").check()
    page.get_by_role("option", name="A", exact=True).get_by_role("checkbox").check()
    page.get_by_role("option", name="A", exact=True).get_by_role("checkbox").press("Escape")
    page.locator("#productionStartYear").click()
    page.locator("#productionStartYear").fill("2000")
    page.locator("#parametersForm div").filter(has_text="Утвержден проект на разработку технологии геологического изучения, разведки и до").nth(1).click()
    page.get_by_role("option", name="Да").click()
    page.get_by_text("Не определено").first.click()
    page.get_by_role("option", name="Да").click()
    page.get_by_text("Не определено").first.click()
    page.get_by_role("option", name="Да").click()
    page.get_by_text("Да", exact=True).nth(1).press("Tab")
    page.get_by_text("Не определено").press("Enter")
    page.get_by_role("option", name="Не определено").press("ArrowUp")
    page.get_by_role("option", name="Нет").press("Enter")
    expect(page.get_by_role("button", name="Сохранить")).to_be_visible()
    expect(page.get_by_role("button", name="Сохранить")).to_be_editable()
    page.get_by_role("button", name="Сохранить").click()
    time.sleep(3)
    del_project(page)

    context.close()
    browser.close()


@pytest.mark.test_all12
@pytest.mark.test_create_projects
def test_projects_page_crate_rkoon(playwright: Playwright) -> None:
    browser, context, page = setup_browser_and_context(playwright)
    # Авторизация
    authorization(page)
    page.get_by_role("button", name="Создать новый проект").click()
    expect(page.get_by_label("Without label")).to_contain_text("РКЗ")
    page.get_by_label("edit project name").click()
    page.get_by_role("main").get_by_placeholder("Найти").fill(BASE_PROJECT_PRMS)
    page.get_by_role("main").get_by_placeholder("Найти").press("Enter")
    expect(page.locator("h2")).to_contain_text(BASE_PROJECT_PRMS)
    page.get_by_label("Without label").click()
    expect(page.get_by_role("option", name="РКЗ")).to_be_visible()
    expect(page.get_by_role("option", name="РКООН")).to_be_visible()
    expect(page.get_by_role("option", name="PRMS")).to_be_visible()
    page.get_by_role("option", name="РКООН").click()
    page.get_by_role("button", name="Добавить").click()
    time.sleep(7)

    page.locator("input[name=\"Месторождение\"]").click()
    page.locator("input[name=\"Месторождение\"]").fill("1")
    page.locator("input[name=\"Месторождение\"]").press("Tab")
    page.locator("div:nth-child(2) > .MuiInputBase-root > .MuiSelect-select").click()
    page.get_by_role("option", name="Газовое", exact=True).click()
    page.locator("input[name=\"Группа эксплуатационных объектов\"]").click()
    page.locator("input[name=\"Группа эксплуатационных объектов\"]").fill("1")
    page.locator("input[name=\"Группа эксплуатационных объектов\"]").press("Tab")
    page.locator("input[name=\"Эксплуатационный объект\"]").click()
    page.locator("input[name=\"Эксплуатационный объект\"]").fill("1")
    page.locator("input[name=\"Эксплуатационный объект\"]").press("Tab")
    page.locator("input[name=\"Пласт\"]").click()
    page.locator("input[name=\"Пласт\"]").fill("1")
    page.locator("input[name=\"Пласт\"]").press("Tab")
    page.locator("input[name=\"Залежь\"]").click()
    page.locator("input[name=\"Залежь\"]").fill("1")
    page.locator("input[name=\"Залежь\"]").press("Tab")
    expect(page.get_by_role("button", name="Дополнительные параметры")).to_be_visible()
    page.get_by_role("button", name="Дополнительные параметры").click()
    page.locator("input[name=\"Страна\"]").click()
    page.get_by_role("option", name="Куба").click()
    page.locator("div:nth-child(2) > .MuiAutocomplete-root > .MuiFormControl-root > .MuiInputBase-root").click()
    page.locator("input[name=\"Регион\"]").fill("1")
    page.locator("input[name=\"Регион\"]").press("Tab")
    page.locator("input[name=\"Собственник\"]").click()
    page.locator("input[name=\"Собственник\"]").fill("1")
    page.locator("input[name=\"Собственник\"]").press("Tab")
    page.locator("#percentOwn").click()
    page.locator("#percentOwn").fill("1")
    page.locator("#percentOwn").press("Tab")
    page.locator("input[name=\"Недропользователь\"]").fill("1")
    page.locator("input[name=\"Недропользователь\"]").press("Tab")
    page.locator("input[name=\"Оператор\"]").fill("1")
    page.locator("input[name=\"Оператор\"]").press("Tab")
    page.locator("input[name=\"Лицензионный участок\"]").fill("1")
    page.locator("input[name=\"Лицензионный участок\"]").press("Tab")
    page.locator("input[name=\"Лицензионные обязательства \\/ ограничения\"]").click()
    page.locator("input[name=\"Лицензионные обязательства \\/ ограничения\"]").fill("1")
    page.locator("input[name=\"Лицензионные обязательства \\/ ограничения\"]").press("Enter")
    page.locator("#yearOpen").click()
    page.locator("#yearOpen").fill("2000")
    page.locator("#yearOpen").press("Enter")
    page.locator("input[name=\"Метод подсчета\"]").click()
    page.get_by_role("option", name="Объемный", exact=True).click()
    page.locator("input[name=\"Метод подсчета\"]").press("Enter")
    page.locator("input[name=\"Организация\\, выполнившая оценку\"]").click()
    page.get_by_role("option", name="Выгон Консалт", exact=True).click()
    page.locator("input[name=\"Отвественный исполнитель подсчета\"]").click()
    page.get_by_role("option", name="Отвественный исполнитель подсчета").click()
    page.locator("input[name=\"Отвественный исполнитель подсчета\"]").press("Enter")
    expect(page.get_by_role("dialog")).to_contain_text("Далее")
    page.get_by_role("button", name="Далее").click()
    expect(page.get_by_text("Полезное ископаемое*")).to_be_visible()
    expect(page.locator("div").filter(has_text=re.compile(r"^Класс\*$")).locator("span")).to_be_visible()
    expect(page.get_by_text("Подкласс")).to_be_visible()
    expect(page.get_by_text("Категория E*")).to_be_visible()
    expect(page.get_by_text("Категория F*")).to_be_visible()
    expect(page.get_by_text("Категория G*")).to_be_visible()
    expect(page.get_by_text("Год начала добычи")).to_be_visible()
    expect(page.get_by_text("Утвержден проект на разработку технологии геологического изучения, разведки и до")).to_be_visible()
    expect(page.get_by_text("Объект перевода вскрыт транзитным фондом*")).to_be_visible()
    page.locator("div:nth-child(2) > .MuiInputBase-root > .MuiSelect-select").first.click()
    page.get_by_text("Нефть, тыс.т").click()
    page.get_by_role("option", name="Растворенный газ, млн.м").get_by_role("checkbox").check()
    page.get_by_role("option", name="Газовая шапка, млн.м").get_by_role("checkbox").check()
    page.get_by_role("option", name="Газ свободный, млн.м").get_by_role("checkbox").check()
    page.get_by_role("option", name="Газ свободный, млн.м").press("Escape")
    page.locator("#parametersForm > div > div:nth-child(2) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select").click()
    page.get_by_role("option", name="Жизнеспособные", exact=True).click()
    page.locator("div:nth-child(3) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select").click()
    page.get_by_role("option", name="Действующие").click()
    page.locator("div:nth-child(4) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select").click()
    page.get_by_role("option", name="1,2").click()
    page.locator("div:nth-child(5) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select").click()
    page.get_by_role("option", name="1,1").click()
    page.locator("div:nth-child(6) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select").click()
    page.get_by_role("option", name="2").click()
    page.locator("#productionStartYear").click()
    page.locator("#productionStartYear").fill("2000")
    page.locator("#productionStartYear").press("Tab")
    page.get_by_text("Не определено").first.press("Enter")
    page.get_by_role("option", name="Не определено").press("ArrowUp")
    page.get_by_role("option", name="Нет").press("ArrowUp")
    page.get_by_role("option", name="Да").press("Enter")
    page.locator("#parametersForm").get_by_text("Да", exact=True).press("Tab")
    page.locator('//*[@id="parametersForm"]/div/div[9]/div[2]/div').click()
    page.get_by_role("option", name="Да").press("Enter")
    expect(page.get_by_role("button", name="Назад")).to_be_visible()
    expect(page.get_by_label("close")).to_be_visible()
    expect(page.get_by_role("dialog")).to_contain_text("Сохранить")
    page.get_by_role("button", name="Сохранить").click()
    time.sleep(5)
    del_project(page)


    context.close()
    browser.close()